config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  get 'home/checkout', to: "home#checkout", as:"checkout"
  post 'home/cart/:product',to: "home#cart",as:"add_to_cart"
  get 'home/pay',to:'home#pay',as:"confirmed_order"
  get 'home/reset',to:'home#reset',as:"reset_order"
  get 'home/orders',to:'home#orders',as:'my_orders'
  get 'home/bills/:id',to:'home#bills',as:'view_bill'
  get 'orders',to:'home#all_orders',as:'all_orders' 
  get 'show',to:'home#show',as:'show_product'
  post 'home/search',to:'home#search',as:'search_product'
  patch 'updatecount',to:'guitars#count_update',as:'count_update'
  patch 'updatecountaccessories',to:'accessories#count_update',as:'count_update_accessory'
  post 'delete_item/:index',to:'home#delete',as:'delete_item'
  devise_for :users
  resources :accessories
  resources :guitars
  resources :images
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_carousel.html.erb
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  


  <div class="carousel-inner">
    
  <%images.each_with_index do |img,idx|%>

    <div class="carousel-item <%='active' if idx==0%>">
      <%=image_tag img.location.to_s,class:"d-block w-100"%>
    </div>
  <%end%>  
 
  </div>




</div>

app/views/shared/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
        <small class="d-block mb-3 text-muted"><%=Platipus::Renderer.copyright 'Faraz Noor', 'All rights reserved'%></small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Product Catalog</a></li>
          <li><a class="text-muted" href="#">Carousel</a></li>
          <li><a class="text-muted" href="#">Dynamic Invoice</a></li>
          <li><a class="text-muted" href="#">Sellers DashBoard</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Ruby On Rails</a></li>
          <li><a class="text-muted" href="#">Postgresql</a></li>
          <li><a class="text-muted" href="#">Ajax</a></li>
          <li><a class="text-muted" href="#">Bootstrap</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="http://faraznoor.live">Faraz Noor</a></li>
          <li><a class="text-muted" href="https://github.com/stingrayzboy">GitHub</a></li>
          <li><a class="text-muted" href="https://linkedin.com/in/go-get-faraz">Linked In</a></li>
        </ul>
      </div>
    </div>
  </footer>
  <!-- Container ends it began in index.html.erb -->
</div>
    

app/views/shared/_guitar_iterator.html.erb
	<table class="table">
		  <thead>
		    <tr>
		   		<th scope="col">Item</th>
				<th scope="col">Model</th>
				<th scope="col">Brand</th>
				<th scope="col">Serial</th>
		    </tr>
		  </thead>
		  <tbody>
		  	<%guitar.each_with_index do |p,idx|%>
		  		<tr>
			      <th scope="row"><%=idx+1%></th>
			      <td><%=p.model%></td>
			      <td><%=p.brand%></td>
			      <td><%=p.serial.upcase%></td>
			    </tr>

		  	<%end%>
		  </tbody>
		</table>

app/views/shared/_invoice.html.erb
<div class="text-center"><input type="button" onclick="printDiv('printableArea')" value="Print Invoice" class="btn btn-outline-success" /></div>

<div class="container" id="printableArea">

<style>
    .invoice-box {
        max-width: 800px;
        margin: auto;
        padding: 30px;
        border: 1px solid #eee;
        box-shadow: 0 0 10px rgba(0, 0, 0, .15);
        font-size: 16px;
        line-height: 24px;
        font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        color: #555;
    }
    
    .invoice-box table {
        width: 100%;
        line-height: inherit;
        text-align: left;
    }
    
    .invoice-box table td {
        padding: 5px;
        vertical-align: top;
    }
    
    .invoice-box table tr td:nth-child(2) {
        text-align: right;
    }
    
    .invoice-box table tr.top table td {
        padding-bottom: 20px;
    }
    
    .invoice-box table tr.top table td.title {
        font-size: 45px;
        line-height: 45px;
        color: #333;
    }
    
    .invoice-box table tr.information table td {
        padding-bottom: 40px;
    }
    
    .invoice-box table tr.heading td {
        background: #eee;
        border-bottom: 1px solid #ddd;
        font-weight: bold;
    }
    
    .invoice-box table tr.details td {
        padding-bottom: 20px;
    }
    
    .invoice-box table tr.item td{
        border-bottom: 1px solid #eee;
    }
    
    .invoice-box table tr.item.last td {
        border-bottom: none;
    }
    
    .invoice-box table tr.total td:nth-child(2) {
        border-top: 2px solid #eee;
        font-weight: bold;
    }
    
    @media only screen and (max-width: 600px) {
        .invoice-box table tr.top table td {
            width: 100%;
            display: block;
            text-align: center;
        }
        
        .invoice-box table tr.information table td {
            width: 100%;
            display: block;
            text-align: center;
        }
    }
    
    /** RTL **/
    .rtl {
        direction: rtl;
        font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
    }
    
    .rtl table {
        text-align: right;
    }
    
    .rtl table tr td:nth-child(2) {
        text-align: left;
    }
</style>
	<!-- Container is closed in foother dont close this div -->
	<div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="top">
                <td colspan="2">
                    <table>
                        <tr>
                            <td class="title">
                                <img src="<%=asset_path('guitarzone_logo.jpg')%>" style="width:100%; max-width:300px;">
                            </td>
                            
                            <td>
                                Invoice #: <%=invoice.purchase_id%><br>
                                Created: <%=invoice.created_at.in_time_zone("Chennai").strftime("%d/%m/%Y %I:%M%p")%><br>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr class="information">
                <td colspan="2">
                    <table>
                        <tr>
                            <td>
                                GuitarZone, Inc.<br>
                                Lucknow<br>
                                India
                            </td>
                            
                            <td>
                            	Deliver to:<br>
                                <%=invoice.user.name%><br>
                                <%=invoice.user.address%><br>
                                <%=invoice.user.city%><br>
                                <%=invoice.user.country%><br>
                                <%=invoice.user.pin_code%><br>
                                <%=invoice.user.email%>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr class="heading">
                <td>
                    Item
                </td>
                
                <td>
                    Price
                </td>
            </tr>
            <%total=0%>
            <%purchases.each do |purchase|%>
            
            <tr class="item">
                <td>
                    <%=purchase.product.type=='Guitar'? purchase.product.model : purchase.product.name %>
                </td>
                
                <td>
                    <%=purchase.product.price%>
                </td>
                <%total+=purchase.product.price%>
            </tr>
            
            <%end%>
            
            <tr class="total">
                <td></td>
                
                <td>
                   Total: ₹<%=total%>
                </td>
            </tr>
        </table>
        
        <script type="text/javascript">
            function printDiv(divName) {
                 var printContents = document.getElementById(divName).innerHTML;
                 var originalContents = document.body.innerHTML;

                 document.body.innerHTML = printContents;

                 window.print();

                 document.body.innerHTML = originalContents;
            }
        </script>

app/views/shared/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal">Guitar Zone</h5>
      	
      	<%unless logged_in?(:owner)%>
      		<%=form_tag search_product_path,class:"form-inline mt-2 mt-md-0 text-center" do%>
      			<%=text_field_tag :query,params['query'],class:"form-control mr-sm-2" %>
      			<%=button_tag(type: 'submit',class:"btn btn-outline-primary my-2 my-sm-0") do
  					content_tag(:strong, '<i class="fa fa-search"></i>'.html_safe)
				end%>
      		<%end%>
	    </form>	
      	
      	<%end%>
      	

      	<nav class="my-2 my-md-0 mr-md-3">       
		    
		    <%=link_to :Home, root_path,class:"p-2 text-dark"%>
		    
			<%if current_user%>
					<%if logged_in?(:owner)%>
						<%=link_to :Guitars,guitars_path,class:"p-2 text-dark"%>
						<%=link_to :Accessories,accessories_path,class:"p-2 text-dark"%>
						<%=link_to :Invoices,all_orders_path,class:"p-2 text-dark"%>
					<%else%>
						
						<%=link_to "Cart#{(': '+session[:cart].size.to_s) if session[:cart].size>0}",checkout_path,class:"p-2 text-dark",id:"cart"%>
						<%=link_to "My Orders",my_orders_path,class:"p-2 text-dark"%>
					<%end%>
		</nav>
					<%=link_to :Logout, destroy_user_session_path , method: :delete,class:"btn btn-outline-danger"%>
			<%else%>
					<%=link_to :Login, new_user_session_path,class:"btn btn-outline-success"%>
			<%end%>   
</div>

app/views/shared/_show_product.html.erb
	<style type="text/css">
		.carousel-control-next-icon {
		  background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23000' viewBox='0 0 8 8'%3E%3Cpath d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E");
		}
		.carousel-control-prev-icon {
		  background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23000' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E");
		}
	</style>
	<div class="row">
		<div class="col col-md-6">
			
			
			<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
			  <ol class="carousel-indicators">
			   <%product.images.each_with_index do |img,idx|%>
				    <li data-target="#carouselExampleIndicators" data-slide-to="<%=idx%>" <%='class="active"' if idx==0%>></li>
			    <%end%>
			  </ol>
			  <div class="carousel-inner" style="height: 500px;">
			  <%product.images.each_with_index do |img,idx|%>
				  
				    <div class="carousel-item <%='active' if idx==0 %>">
				    	<%=image_tag img.location.to_s,class:"d-block w-100"%>
				    </div>
				  
			  <%end%>
			  </div>
			  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
			    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
			    <span class="carousel-control-next-icon" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			  </a>
			</div>
		</div>
		<div class="col col-md-6">
			<%if product.class.to_s=='Guitar'%>
				<p>
				  <strong>Model:</strong>
				  <%= product.model %>
				</p>

				<p>
				  <strong>Brand:</strong>
				  <%= product.brand %>
				</p>

				<p>
				  <strong>Price:</strong>
				  <%= product.price %>
				</p>

				<p>
				  <strong>Serial:</strong>
				  <%= product.serial %>
				</p>

				<p>
				  <strong>Guitar type:</strong>
				  <%= product.guitar_type %>
				</p>
			<%else%>
				<p>
				  <strong>Name:</strong>
				  <%= product.name %>
				</p>

				<p>
				  <strong>Price:</strong>
				  <%= product.price %>
				</p>

				<p>
				  <strong>Characteristic:</strong>
				  <%= product.characteristic %>
				</p>
			<%end%>
			<%="<p><strong>This Product is out of stock</strong></p>".html_safe unless product.accessory_count>0%>
			<%=link_to "Add to Cart",add_to_cart_path(product),class:"btn btn-lg btn-block btn-outline-primary #{'disabled' unless product.accessory_count>0}",method: :post,remote: true unless logged_in?(:owner)%>
					
		</div>
	</div>