config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  get 'home/checkout', to: "home#checkout", as:"checkout"
  post 'home/cart/:product',to: "home#cart",as:"add_to_cart"
  get 'home/pay',to:'home#pay',as:"confirmed_order"
  get 'home/reset',to:'home#reset',as:"reset_order"
  get 'home/orders',to:'home#orders',as:'my_orders'
  get 'home/bills/:id',to:'home#bills',as:'view_bill'
  get 'orders',to:'home#all_orders',as:'all_orders' 
  get 'show',to:'home#show',as:'show_product'
  post 'home/search',to:'home#search',as:'search_product'
  patch 'updatecount',to:'guitars#count_update',as:'count_update'
  patch 'updatecountaccessories',to:'accessories#count_update',as:'count_update_accessory'
  post 'delete_item/:index',to:'home#delete',as:'delete_item'
  devise_for :users
  resources :accessories
  resources :guitars
  resources :images
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!,except:[:index,:show,:search]
  
  def index
    if logged_in?(:owner)
      @unsold_guitars=Guitar.where(sold:0)
      @sold_guitars=Guitar.where(sold:1)
      @accessories=Accessory.all
      #get the accessory key values
      @pie_chart=Product.all.select(:name,:accessory_count).pluck(:name,:accessory_count).to_h.reject{|k| k.nil?}
      #get the guitar key values
      @pie_chart.merge!(Product.all.select(:model,:accessory_count).pluck(:model,:accessory_count).to_h.reject{|k| k.nil?})

      #byebug
    else
      unless session[:cart]
    	 session[:cart]=[]
      end
    	@products=Product.where("accessory_count > '0'").includes(:images)
    	#byebug
    end
  end
  def show
    id=params[:id]
    @product=Product.find(id)
  end
  def delete
    session[:cart].delete_at(params[:index].to_i)
    redirect_to checkout_path
  end
  def search
    @products=[]
    Product.all.includes(:images).each do |prod|
      prod.search_token.split('|').each do |token|
        if token.upcase.include?(params['query'].strip.upcase)
          @products<<prod
          break
        end 
      end
    end
    unless @products.empty?
      if @products.count==1
        @product=@products.first
        render :show
      else
        logger.info"Found something #{@products}"
        render :index
      end
    else
      
    end
  end


  def cart
    session[:cart]<<params[:product]

  end

  def checkout
  	#byebug
  	logger.info(session[:cart])
  	if session[:cart].first.nil?
  		@message=""
      @flag=true
  	else
  		@products=[]
      session[:cart].each do |prod|
        @products<<Product.find(prod)
      end 
      @message="Items in your Cart"
  	end
  end

  def pay
  begin 
    last_purchase=Purchase.last
    if last_purchase.nil?
      purc=0
    else
      purc=last_purchase.purchase_id.to_i
    end
    session[:cart].each do|p|
      product=Product.find(p)

      if product[:accessory_count]>0
        @p=Purchase.create!(purchase_id:purc+1,product:product,user:current_user)
        
        product.type=='Guitar' ? product.update(accessory_count:(product.accessory_count-1),sold:1) : product.update(accessory_count:(product.accessory_count-1))
        

      else
        @notice='Some Products Couldnot be billed as they went out of Stock.Your Total amount got revised.' 
      end

    end
    @purchases=Purchase.where(purchase_id:@p.purchase_id).includes(:product)
  rescue
    redirect_to root_path
  end
    session[:cart]=[]
  end

  def reset
    session[:cart]=[]
    redirect_to root_path
  end

  def orders
    @p=Purchase.select("DISTINCT(purchase_id)").where(user:current_user).order(created_at: :desc).pluck(:purchase_id).uniq
  end

  def all_orders
    if logged_in?(:owner)
      @p=nil
      @p=Purchase.select("DISTINCT(purchase_id)").order(created_at: :desc).pluck(:purchase_id).uniq
      @p.flatten!
      #byebug
      render :orders
    else
      redirect_to root_path
    end
  end

  def bills
    @purchasess=Purchase.where(purchase_id:params[:id]).includes(:product)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/bills.html.erb
<div class="container">
	<!-- dont close the container div its closed in the footer -->
	<%=render partial:'shared/invoice',locals:{invoice:@purchasess.last,purchases:@purchasess}%>

app/views/home/cart.js.erb
$("#cart").html("Cart: <%=session[:cart].size%>");

app/views/home/checkout.html.erb
<div class="container">
	<!-- This div is ended in Footer -->
	<div class="text-center">
		<h1><%=@message%></h1>
		<% if @flag %>
			<%= image_tag asset_path('empty_cart.png'),height:"50%"%>
		<%end%>

		<%if @products%>
			<table class="table">
			  <thead>
			    <tr>
			      <th scope="col">#</th>
			      <th scope="col">Item</th>
			      <th scope="col">Name/Model</th>
			      <th scope="col">Price</th>
			      <th scope="col">Remove</th>
			    </tr>
			  </thead>
			  <tbody>
			  	<%total=0%>
			  	<%@products.each_with_index do |p,idx|%>
			  		<tr>
				      <th scope="row"><%=idx+1%></th>
				      <td><%=p.type.to_s%></td>
				      <td><%=p.type.to_s == 'Guitar' ? p.model : p.name %></td>
				      <td><%=p.price%></td>
				      <td><%=link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe,delete_item_path(idx),method: :post%></td>
				      <%total+=p.price%>
				    </tr>

			  	<%end%>
			    <tr class="text-right">
			    	<td colspan="4">Total: <%=total%></td>
			    </tr>
			  </tbody>
			</table>
			<%=link_to "Checkout",confirmed_order_path,class:"btn btn-outline-success" %>
			<%=link_to "Reset Order",reset_order_path,class:"btn btn-outline-danger"%>
		<%end%>
	</div>

app/views/home/index.html.erb
<%if logged_in?(:owner)%>
	<%=render partial:'home/owner/dashboard',locals:{unsold:@unsold_guitars,sold:@sold_guitars,accessories:@accessories}%>
<%else%>
<script type="text/javascript">
	function open_product(p){
		window.open('<%=show_product_path%>'+'?'+'id='+p,'_self');
	}
</script>	

	<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Encore!</h1>
      <p class="lead">Where the path leads to...</p>
    </div>

    <div class="container">
    	<!-- This is where the container starts it ends in _footer.html.erb -->
    <div class="card-deck mb-3 text-center">

    <%@products.each do |p|%>

    	<%if p.type.to_s=="Guitar"%>

       
	        <div class="card mb-4 box-shadow">
	          <div class="card-header">
	            <h4 class="my-0 font-weight-normal"><%=p.model%></h4>
	          </div>
	          <div class="card-body">
	            <h1 class="card-title pricing-card-title">₹<%=p.price%></h1>
	            
	            <div style="height:300px" onclick="open_product(<%=p.id%>)">
	            	<%=render partial:"shared/carousel",locals:{images:p.images}%>	
	            </div>

	            <%=link_to_if !(session[:cart].include?(p.id)),"Add to Cart",add_to_cart_path(p),class:"btn btn-lg btn-block btn-outline-primary #{'disabled' unless p.accessory_count>0}",method: :post,remote: true%>
	            <!-- <button type="button" class="btn btn-lg btn-block btn-outline-primary">Add To Cart</button> -->
	          </div>
	        </div>
    	


    	<%else%>



    		<div class="card mb-4 box-shadow">
	          <div class="card-header">
	            <h4 class="my-0 font-weight-normal"><%=p.name%></h4>
	          </div>
	          <div class="card-body">
	            <h1 class="card-title pricing-card-title">₹<%=p.price%></h1>
	            

	            <div style="height:300px" onclick="open_product(<%=p.id%>)">
	            	<%=render partial:"shared/carousel",locals:{images:p.images}%>
	            </div>


	            <%=link_to_if (p.accessory_count>0),"Add to Cart",add_to_cart_path(p),class:"btn btn-lg btn-block btn-outline-primary #{'disabled' unless p.accessory_count>0}",method: :post,remote: true%>
	            <!-- <button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</button> -->
	          </div>
	        </div>

    	<%end%>
    <%end%>


    	<%res=@products.count%>
    	<%(res==0 ? 3 : (res<3 ? 3-res: (res%3==0 ? 3 : res/3))).times do %>

    		<div class="card mb-4 box-shadow">
	          <div class="card-header">
	            <h4 class="my-0 font-weight-normal">Your Ad Here for </h4>
	          </div>
	          <div class="card-body">
	            <h1 class="card-title pricing-card-title">₹1000 per ad</h1>
	            

	            <div style="height:300px">
	            	<img src="<%=asset_path('image.jpg')%>" class="d-block w-100">
	            </div>



	            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</button>
	          </div>
	        </div>

    	<%end%>
    </div>
<%end%>

app/views/home/orders.html.erb
<div class="container">
	<!-- no need to end container its closed in footer -->
	
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Invoice No.</th>
      <th scope="col">Date</th>
      <th scope="col">Open</th>
    </tr>
  	</thead>
  	<tbody>
	  	<%@p.each_with_index do |p,idx|%>
			<tr>
		      <th scope="row"><%=idx+1%></th>
		      <td><%=p%></td>
		      <td><%=Purchase.where(purchase_id:p).select(:created_at).last[:created_at].in_time_zone("Chennai").strftime("%d/%m/%Y %I:%M%p")%></td>
		      <td><%=link_to "Invoice No: #{p}",view_bill_path(p),class:"btn btn-outline-primary"%><br></td>
		    </tr>
		<%end%>
	</tbody>   
</table>


	

app/views/home/pay.html.erb
<p id="notice text-center"><%= @notice unless @notice.nil?%></p>
<%=render partial:'shared/invoice',locals:{invoice:@p,purchases:@purchases}%>

app/views/home/search.html.erb
<div class="container text-center">
<img src="<%=asset_path('404.png')%>"/>

app/views/home/show.html.erb
<div class="container">
<%=render partial:"shared/show_product",locals:{product:@product}%>