config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  get 'home/checkout', to: "home#checkout", as:"checkout"
  post 'home/cart/:product',to: "home#cart",as:"add_to_cart"
  get 'home/pay',to:'home#pay',as:"confirmed_order"
  get 'home/reset',to:'home#reset',as:"reset_order"
  get 'home/orders',to:'home#orders',as:'my_orders'
  get 'home/bills/:id',to:'home#bills',as:'view_bill'
  get 'orders',to:'home#all_orders',as:'all_orders' 
  get 'show',to:'home#show',as:'show_product'
  post 'home/search',to:'home#search',as:'search_product'
  patch 'updatecount',to:'guitars#count_update',as:'count_update'
  patch 'updatecountaccessories',to:'accessories#count_update',as:'count_update_accessory'
  post 'delete_item/:index',to:'home#delete',as:'delete_item'
  devise_for :users
  resources :accessories
  resources :guitars
  resources :images
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessory.rb
class Accessory < Product
	validates :name, presence: true
	validates :characteristic, presence: true
	validates :price, presence: true
	validates :accessory_count, presence: true	

	before_save :tokenization

	def tokenization
		self.search_token="#{self.name}|#{self.characteristic}"
	end
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_accessory, only: [:show, :edit, :update, :destroy]
  access all:[:index] , owner: :all
  # GET /accessories
  # GET /accessories.json
  def index
    @accessories = Accessory.all
  end

  # GET /accessories/1
  # GET /accessories/1.json
  def show
    #@accessory_images = @accessory.images.all
  end
  def count_update
    Accessory.find(params[:accessory][:id]).update(accessory_count:params[:accessory][:accessory_count])
  end
  # GET /accessories/new
  def new
    @accessory = Accessory.new
    @accessory_images = @accessory.images.build
  end

  # GET /accessories/1/edit
  def edit
  end

  # POST /accessories
  # POST /accessories.json
  def create
    @accessory = Accessory.new(accessory_params)

    respond_to do |format|
      if @accessory.save

        params[:images]['location'].each do |a|
          @post_attachment = @accessory.images.create!(:location => a,:imageable_id => @accessory.id, :imageable_type => @accessory.class.to_s)
        end


        format.html { redirect_to @accessory, notice: 'Accessory was successfully created.' }
        format.json { render :show, status: :created, location: @accessory }
      else
        format.html { render :new }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accessories/1
  # PATCH/PUT /accessories/1.json
  def update
    
      if @accessory.update(accessory_params)
        params[:images]['location'].each_with_index do |a,idx|
          unless @accessory.images[idx].nil?
              @post_attachment = @accessory.images[idx].update(:location => a)  
          else
              @post_attachment = @accessory.images.create!(:location => a,:imageable_id => @accessory.id, :imageable_type => @accessory.class.to_s)
          end
        end
        respond_to do |format|
          format.html { redirect_to @accessory, notice: 'Accessory was successfully updated.' }
          format.json { render :show, status: :ok, location: @accessory }
        end
        else
        respond_to do |format|
          format.html { render :edit }
          format.json { render json: @accessory.errors, status: :unprocessable_entity }
        end
    end
  end

  # DELETE /accessories/1
  # DELETE /accessories/1.json
  def destroy
    @accessory.destroy
    respond_to do |format|
      format.html { redirect_to accessories_url, notice: 'Accessory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accessory
      @accessory = Accessory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accessory_params
      params.require(:accessory).permit(:name, :price, :characteristic,:accessory_count, images_attributes: 
  [:id, :imageable_id,:imageable_type, :location])
    end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/views/accessories/_form.html.erb
<%= form_with(model: accessory, local: true) do |form| %>
  <% if accessory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(accessory.errors.count, "error") %> prohibited this accessory from being saved:</h2>

      <ul>
      <% accessory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_area :name, id: :accessory_name,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :accessory_price,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :characteristic %>
    <%= form.text_area :characteristic, id: :accessory_characteristic ,class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :accessory_count %>
    <%= form.number_field :accessory_count, id: :accessory_count,class:"form-control" %>
  </div>

  <%= form.fields_for :images do |p| %>
     <div class="form-group">
       <%= p.label :location %><br>
       <%= p.file_field :location, :multiple => true, name:     "images[location][]",class:"form-control" %>
     </div>
   <% end %>

  <div class="actions">
    <%= form.submit "Submit",class:"btn btn-outline-success" %>
  </div>
<% end %>

app/views/accessories/edit.html.erb
<div class="container">
<h1>Editing Accessory</h1>

<%= render 'form', accessory: @accessory %>

<%= link_to 'Show', @accessory %> |
<%= link_to 'Back', accessories_path %>

app/views/accessories/index.html.erb
<div class="container">
<%if logged_in?(:owner)%>


<p id="notice"><%= notice %></p>

<h1>Accessories</h1>
<%= link_to 'New Accessory', new_accessory_path %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Characteristic</th>
      <th scope="col">Qty</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @accessories.each do |accessory| %>
      <tr>
        <td><%= accessory.name %></td>
        <td><%= accessory.price %></td>
        <td><%= accessory.characteristic %></td>
        <%=form_for accessory,url:count_update_accessory_path do |f|%>
          <%=f.hidden_field :id,value:accessory.id%>
           <td><%= f.number_field :accessory_count, id: :accessory_count ,class:"form-control"%></td>
        <%end%>
        <td><%= link_to 'Show', accessory %></td>
        <td><%= link_to 'Edit', edit_accessory_path(accessory) %></td>
        <td><%= link_to 'Destroy', accessory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%else%>
  <div class="text-center">
    <h1>You are not authorized here</h1>
    <%= image_tag asset_path('unauthorized.png'),height:"50%"%>
  </div>
<%end%>

app/views/accessories/new.html.erb
<div class="container">
<h1>New Accessory</h1>

<%= render 'form', accessory: @accessory %>

<%= link_to 'Back', accessories_path %>

app/views/accessories/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<%=render partial:"shared/show_product",locals:{product:@accessory}%>
<%= link_to 'Edit', edit_accessory_path(@accessory) %> |
<%= link_to 'Back', accessories_path %>